[news_issue]
title = "Circle Chart ─ News ─ Issue"
url = "https://circlechart.kr/page_article/list.circle?sgenre=issue"
entrySelector = "aside#pc_content_list > article"
titleSelector = "a > section.text-lg.font-bold.cursor-pointer"
linkSelector = "a"
contentSelector = "section > div[class='basis-4/5 pl-4 text-gray-500 cursor-pointer']"
imageSelector = "section > div[class='basis-1/5 h-[100px] cursor-pointer']"
waitUntil = "networkidle"
