[news_opinion]
title = "Circle Chart ─ News ─ Opinion"
url = "https://circlechart.kr/page_article/list.circle?sgenre=opinion"
entrySelector = "aside#pc_content_list > article"
titleSelector = "a > section.text-lg.font-bold.cursor-pointer"
linkSelector = "a"
dateSelector = "div > span"
dateFormat = "yyyy-MM-dd"
contentSelector = "section > div[class='basis-4/5 pl-4 text-gray-500 cursor-pointer']"
imageSelector = "section > div[class='basis-1/5 h-[100px] cursor-pointer']"
waitUntil = "networkidle"

[news_album]
title = "Circle Chart ─ News ─ Album"
url = "https://circlechart.kr/page_article/list.circle?sgenre=album"
entrySelector = "aside#pc_content_list > article"
titleSelector = "a > section.text-lg.font-bold.cursor-pointer"
linkSelector = "a"
dateSelector = "div > span"
dateFormat = "yyyy-MM-dd"
contentSelector = "section > div[class='basis-4/5 pl-4 text-gray-500 cursor-pointer']"
imageSelector = "section > div[class='basis-1/5 h-[100px] cursor-pointer']"
waitUntil = "networkidle"

[news_kpop]
title = "Circle Chart ─ News ─ K-pop now"
url = "https://circlechart.kr/page_article/list.circle?sgenre=kpop"
entrySelector = "aside#pc_content_list > article"
titleSelector = "a > section.text-lg.font-bold.cursor-pointer"
linkSelector = "a"
dateSelector = "div > span"
dateFormat = "yyyy-MM-dd"
contentSelector = "section > div[class='basis-4/5 pl-4 text-gray-500 cursor-pointer']"
imageSelector = "section > div[class='basis-1/5 h-[100px] cursor-pointer']"
waitUntil = "networkidle"

[news_perform]
title = "Circle Chart ─ News ─ Perform"
url = "https://circlechart.kr/page_article/list.circle?sgenre=perform"
entrySelector = "aside#pc_content_list > article"
titleSelector = "a > section.text-lg.font-bold.cursor-pointer"
linkSelector = "a"
dateSelector = "div > span"
dateFormat = "yyyy-MM-dd"
contentSelector = "section > div[class='basis-4/5 pl-4 text-gray-500 cursor-pointer']"
imageSelector = "section > div[class='basis-1/5 h-[100px] cursor-pointer']"
waitUntil = "networkidle"


[news_issue]
title = "Circle Chart ─ News ─ Issue"
url = "https://circlechart.kr/page_article/list.circle?sgenre=issue"
entrySelector = "aside#pc_content_list > article"
titleSelector = "a > section.text-lg.font-bold.cursor-pointer"
linkSelector = "a"
dateSelector = "div > span"
dateFormat = "yyyy-MM-dd"
contentSelector = "section > div[class='basis-4/5 pl-4 text-gray-500 cursor-pointer']"
imageSelector = "section > div[class='basis-1/5 h-[100px] cursor-pointer']"
waitUntil = "networkidle"
